set windows-shell := ["pwsh", "-NoProfile", "-Command"]

chapter-0 *args:
    cargo run --bin chapter-0 -- {{args}}

chapter-1 *args:
    cargo run --bin chapter-1 -- {{args}}

chapter-2 *args:
    cargo run --bin chapter-2 -- {{args}}

chapter-2-subcommands *args:
    cargo run --bin chapter-2-subcommands -- {{args}}

chapter-2-defaults *args:
    cargo run --bin chapter-2-defaults -- {{args}}

chapter-3-enumerated-values *args:
    cargo run --bin chapter-3-enumerated-values -- {{args}}

chapter-3-validated-values *args:
    cargo run --bin chapter-3-validated-values -- {{args}}